<?php
/** @var array $reports */
?>

<div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4">
    <div>
        <div class="fh-chip d-inline-flex align-items-center gap-2 mb-2">
            <i class="bi bi-file-earmark-bar-graph"></i>
            <span>Report generation</span>
        </div>
        <h1 class="h3 fw-bold text-success fh-section-title mb-1">Reports</h1>
        <p class="fh-muted mb-0">Generate and review system reports.</p>
    </div>
    <a class="btn btn-outline-success" href="<?= e(base_url('dashboard/admin')) ?>">Back to Admin Dashboard</a>
</div>

<div class="fh-card-soft p-4 mb-3">
    <form method="post" action="<?= e(base_url('admin/reports/generate')) ?>" class="row g-3 align-items-end">
        <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
        <div class="col-md-6">
            <label class="form-label">Report type</label>
            <select name="report_type" class="form-select" required>
                <option value="system_summary">System summary</option>
                <option value="bookings_summary">Bookings summary</option>
                <option value="farms_summary">Farms summary</option>
                <option value="users_summary">Users summary</option>
            </select>
        </div>
        <div class="col-md-3 d-grid">
            <button type="submit" class="btn btn-success">
                <i class="bi bi-magic me-2"></i>Generate Report
            </button>
        </div>
    </form>
</div>

<?php if (!empty($reports)): ?>
    <div class="table-responsive">
        <table class="table table-sm align-middle mb-0">
            <thead class="table-light">
            <tr>
                <th>ID</th>
                <th>Type</th>
                <th>Generated by</th>
                <th>Created at</th>
                <th>Payload</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($reports as $r): ?>
                <tr>
                    <td><?= e((string)$r['id']) ?></td>
                    <td><?= e((string)$r['report_type']) ?></td>
                    <td><?= e((string)$r['admin_name']) ?></td>
                    <td><?= e((string)$r['created_at']) ?></td>
                    <td><code class="small"><?= e((string)$r['payload']) ?></code></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="fh-card-soft p-4">No reports yet.</div>
<?php endif; ?>

